// Auto-generated by Task ID 1 — z-ai image-search results.
// Do not edit by hand; re-run the image-gathering task to refresh.
// All URLs are real OSS-hosted results from the z-ai image-search CLI.

export const images = {
  hero:   [
    "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/74259db97743.png",
    "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/23c94288ae47.jpg",
    "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/16618dc84c57.jpg",
  ],
  editorial:   [
    "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/fa72a08d55a5.jpg",
    "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/67caf0f93f40.jpg",
  ],
  products: {
    slipDresses:     [
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/539fae62859c.jpg",
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/fd44570dd438.jpeg",
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/c340e7d960d0.jpg",
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/1b496c415338.jpg",
    ],
    midiDresses:     [
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/ad156a5ea48b.webp",
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/e1b999d72800.jpg",
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/9fafbfe9db67.jpg",
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/bd4ff4324db0.jpg",
    ],
    evening:     [
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/6683cdf2c945.jpg",
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/462e8c5f8013.jpg",
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/e04fff0b7bde.jpg",
    ],
    basics:     [
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/05b0e81e385b.jpg",
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/2e99d4a8b72f.jpg",
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/e17cb5d7ce07.jpg",
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/0bf84617e4e4.jpg",
    ],
    bottoms:     [
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/274fe897b6dc.jpg",
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/8372c43f2c47.jpg",
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/226bc6e7f133.jpg",
    ],
    accessories:     [
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/a5a4b3babb7b.jpg",
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/e1183ce16b25.jpg",
      "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/359b301ef889.jpg",
    ],
  },
  lifestyle:   [
    "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/d4921e96de3f.jpg",
    "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/9a4ed832e947.jpg",
  ],
  lookbook:   [
    "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/5f062dd11dfd.jpg",
    "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/f4e8cb2c9863.jpg",
    "https://z-cdn.chatglm.cn/image-search-mcp/images-ppt/ccbabddc1a2a.jpg",
  ],
} as const;

export type ImageLibrary = typeof images;
